title: Moment Docs
url: http://192.144.230.76:8001/docs/
baseurl: /docs

theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs@v0.4.0.rc1
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
aux_links:
  Moment on GitHub:
    - https://github.com/siriusneo/Moment
permalink: pretty

collections_dir: collections

collections:
  build:
    output: true
  basic:
    output: true
  plugins:
    output: true
  development:
    output: true

just_the_docs:
  collections:
    build:
      name: 从零部署
    basic:
      name: 基本使用与说明
    plugins:
      name: 插件
    development:
      name: 进一步开发

defaults:
  -
    scope: {path: "collections/*"}
    values: {layout: default}

callouts_level: loud

callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  custom:
    title: Custom
    color: pink
    opacity: 0.3
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red

# mermaid:
#   version: "9.1.3"
